#spring.resources.static-locations=classpath:/hello/,classpath:/yizu/
#这个是浏览器地址栏访问的路径localhost:8080/yizu（类似于拦截器）
server:
   context-path: /yizu
#这个是国际化的访问数据的路径
spring:
  messages:
    basename: i18n.login
  #thymeleaf的缓存设置false为禁用true为打开
  thymeleaf:
    cache: false
    # 日期格式化器
  mvc:
    date-format: yyyy-MM-dd
  datasource:
    #   数据源基本配置
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.168.170.192:3306/ggdb
    type: com.alibaba.druid.pool.DruidDataSource
    #   数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
#    schema:
#      - classpath:sql/department.sql
#      - classpath:sql/employee.sql


debug: true
